apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: swift-bridge-test
  annotations:
    argo.octopus.com/project: "Swift Bridge"
    argo.octopus.com/environment: "test"
spec:
  project: default
  source:
     repoURL: https://github.com/OctopusSolutionsEngineering/ghu-swift-bridge.git
     targetRevision: HEAD
     path: Kubernetes/Manifests/test
  destination:
    server: https://kubernetes.default.svc
    namespace: test
  syncPolicy:
    automated:  
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=false
    - CreateNamespace=true